#ifndef DEFINE_H
#define DEFINE_H

enum { // KERNEL FUNCTIONS
    KERNEL_START,
    KERNEL_PARTICLES_TO_CUBE,
    KERNEL_PARTICLES_TO_CUBE_FILLED,
    KERNEL_PARTICLES_TO_SPHERE,
    KERNEL_PARTICLES_TO_SPHERE_FILLED,
    KERNEL_PARTICLES_CLEAN_TIMERS,
    KERNEL_PARTICLES_FOUNTAIN,
    KERNEL_PARTICLES_GRAVITY,

    NO_KERNEL,
};

enum {
    SCRIPT_FOUNTAIN_REBOUND,

    NO_SCRIPT
};

enum { // KERNEL VARIABLES
    GLOBAL_PARTICLE_VECTORS_OBJECT,
    GLOBAL_PARTICLE_TIMERS_OBJECT
};

enum { // INTERPOLARITY VARIABLES
    GLOBAL_PARTICLE_POINTS_OBJECT,

};

enum { // ERROR NAMES
    CL, GL, SDL
};

#endif